### ISSUE TITLE
Router Params changed to {} after first request

### ISSUE THREAD

**Issue by heynikhil** [shiva-rockers/sonicx#1]
`    {
        path: ':iUserId',
        method: 'get',
        controller: (req, res) => {
            console.log(req.params)
            let user = users.find(e => e.birthdate === parseInt(req.params.iUserId))
            if (!user) return res.send('no user')
            res.send(user);
        }
    }`

I am having users list and want to get specific user from my user Array, I am getting the rout params in first try but after first request getting {}.

node -v -- v10.13.0

**Comment by shiva-rockers** [comment]
its is fixed now.
